spring:
  redis:
    database: 0
    host: 192.168.252.94
    port: 6379
    password: sckj
    jedis:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: -1ms
    connect-timeout: 30000ms
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #解决SpringBoot更新后与swagger2不兼容
  swagger:
    enable: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: db1 #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则在未匹配到指定数据源时候使用默认数据源.
      datasource:
        db1:
          url: jdbc:mysql://192.168.232.155:3209/test?useUnicode=true&characterEncoding=utf-8&generateSimpleParameterMetadata=true
          username: root
          password: sckj@155
          driver-class-name: com.mysql.cj.jdbc.Driver
        db2:
          url: jdbc:mysql://192.168.232.155:3209/sys?useUnicode=true&characterEncoding=utf-8&generateSimpleParameterMetadata=true
          username: root
          password: sckj@155
          driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 10 #初始化时建立物理连接的个数
      min-idle: 10 #最小连接池数量
      maxActive: 100 #最大连接池数量
      maxWait: 20000 #获取连接时最大等待时间，单位毫秒
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      time-between-eviction-runs-millis: 20000 #既作为检测的间隔时间又作为test-while-idle执行的依据
      min-evictable-idle-time-millis: 30000 #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      #用来检测连接是否有效的sql
      #mysql中为 select 'x'
      #oracle中为 select 1 from dual
      validation-query: SELECT 'x'
      test-on-borrow: false #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      exception-sorter: true #当数据库抛出不可恢复的异常时,抛弃该连接
      pool-prepared-statements: true #是否缓存preparedStatement,mysql5.5+建议开启
      max-pool-prepared-statement-per-connection-size: 20 #当值大于20时poolPreparedStatements会自动修改为true
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true #合并多个DruidDataSource的监控数据
      #filters通过别名的方式配置扩展插件，常用的插件有：
      #监控统计用的filter:stat 日志用的filter:log4j 防御sql注入的filter:wall
      filters: stat,wall,log4j
      #设置访问druid监控页面的拦截路径及账号和密码,默认没有
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
  autoconfigure:
    # 去除druid配置。是否需要，根据druid连接池的类型。如果druid连接池为starter类型，则需要排除。否则，不需要。
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
# 配置sql打印日志，开发环境需要，生产环境一般不需要
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: wuxx_

#spring:
#  datasource:
#    url: jdbc:mysql://192.168.232.155:3209/test?useUnicode=true&characterEncoding=utf-8&generateSimpleParameterMetadata=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: sckj@155
#    initial-size: 20
#    max-idle: 60
#    max-wait: 10000
#    min-idle: 10
#    max-active: 200
#  jpa:
#    generate-ddl: false
#    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true
#        use-new-id-generator-mappings: false